### ISSUE TITLE
[Bounty]: flow.json Blog Post

### ISSUE THREAD

**Issue by jacob-tucker** [emerald-dao/emerald-academy-v2#32]
# Description
Write a blog detailing all the intricacies of a flow.json file. Specifically,
- What the “accounts” object is for
- How to create an account using Flow CLI and store it in flow.json
- What the “contracts” object is for
- How to use “aliases” under each contract, and why it matters for contract deployment
- How to deploy to emulator/testnet/mainnet using Flow CLI
- How to update contracts using Flow CLI

The blog can be posted wherever, but you just make a PR to add it to this file: https://github.com/emerald-dao/emerald-academy-v2/blob/main/src/lib/content/blogs.ts

# Bounty
20 $FLOW

**Comment by justinthedataboy** [comment]
Good Bid 
Interesting Topic

**Comment by Kiaray** [comment]
Interesting
