### ISSUE TITLE
play.flow.com.   (dot problem!)

### ISSUE THREAD

**Issue by Yumcoder-dev** [emerald-dao/emerald-academy-v2#80]
in the production version, I mean in the following link:
https://academy.ecdao.org/en/catalog/courses/beginner-cadence/chapter2/lesson1

`In order to start making our first Smart Contract, we need to figure out a place to actually put it! To do that, launch a browser of your choice (I would recommend Google Chrome), go to the Flow playground by pasting in this URL: https://play.flow.com./ After you do that, do the following`

there is an additional . at the end of the URL and make problems when opening the playground.

**Comment by jacob-tucker** [comment]
Thank you! This has been fixed: https://github.com/emerald-dao/emerald-academy-v2/commit/b368ad42423f77ba3a4186e1180b18f956df6616
